stages:
  split:
    cmd: python src/data/split.py
    deps:
    - data/raw/raw.csv
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/transform.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    outs:
    - models/best_model.pkl
  training:
    cmd: python src/models/train.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    outs:
    - models/best_model_trained.pkl
  evaluation:
    cmd: python src/models/test.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/best_model_trained.pkl
    metrics:
    - metrics/scores.json:
        cache: false
    outs:
    - data/prediction.csv

    